package v1

#Metadata: {
	// placeholder values, true ones will be generated by Perses when saving the dashboard:
	createdAt: "1970-01-01T00:00:00.000000000Z"
	updatedAt: "1970-01-01T00:00:00.000000000Z"
	version:   1
}
